const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const track=$('#track'),slides=$$('.slide'),dots=$('#dots'),progress=$('#progressBar'),label=$('#progressLabel');let index=0,dragging=false,startX=0,startTranslate=0,wheelLock=false;
function burst(n=16,symbol='♡'){for(let i=0;i<n;i++)setTimeout(()=>heart(symbol),i*35)}
function goTo(n){index=Math.max(0,Math.min(slides.length-1,n));track.style.transform=`translate3d(${-index*100}vw,0,0)`;slides.forEach((s,i)=>{s.classList.toggle('active',i===index);if(i===index){s.querySelectorAll('.reveal').forEach((el,j)=>el.style.transitionDelay=`${Math.min(j*.1,.5)}s`)}});progress.style.width=`${((index+1)/slides.length)*100}%`;label.textContent=`${String(index+1).padStart(2,'0')} / ${String(slides.length).padStart(2,'0')}`;dots.querySelectorAll('.dot').forEach((d,i)=>d.classList.toggle('active',i===index));$('#swipeHint').style.opacity=index>0?'.2':'.8';if(index===slides.length-1)burst(10,'✦')}
slides.forEach((_,i)=>{const d=document.createElement('button');d.className='dot';d.setAttribute('aria-label',`Go to slide ${i+1}`);d.onclick=()=>goTo(i);dots.appendChild(d)});
$('#next').onclick=()=>goTo(index+1);$('#prev').onclick=()=>goTo(index-1);$$('[data-next]').forEach(b=>b.onclick=()=>{unlockMusic();goTo(index+1);burst(10)});$('#restart').onclick=()=>{goTo(0);burst(18)};
window.addEventListener('keydown',e=>{if(e.target.matches('button,input')){if(e.key===' '&&e.target.id==='cake')e.preventDefault();else return}if(['ArrowRight','PageDown'].includes(e.key))goTo(index+1);if(['ArrowLeft','PageUp'].includes(e.key))goTo(index-1);if(e.key===' '&&index===4)blowCake()});
const carousel=$('#carousel');carousel.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;dragging=true;startX=e.clientX;startTranslate=-index*innerWidth;track.style.transition='none';carousel.setPointerCapture(e.pointerId)});carousel.addEventListener('pointermove',e=>{if(!dragging)return;track.style.transform=`translate3d(${startTranslate+e.clientX-startX}px,0,0)`});carousel.addEventListener('pointerup',e=>{if(!dragging)return;dragging=false;track.style.transition='';const dx=e.clientX-startX;if(Math.abs(dx)>55)goTo(index+(dx<0?1:-1));else goTo(index)});carousel.addEventListener('pointercancel',()=>{dragging=false;track.style.transition='';goTo(index)});
carousel.addEventListener('wheel',e=>{if(wheelLock)return;if(Math.abs(e.deltaX)>Math.abs(e.deltaY)||Math.abs(e.deltaY)>45){e.preventDefault();wheelLock=true;goTo(index+(e.deltaY>0||e.deltaX>0?1:-1));setTimeout(()=>wheelLock=false,900)}},{passive:false});
let music=$('#bgMusic'),musicBtn=$('#soundToggle'),musicPaused=false;music.volume=.42;async function playMusic(){try{await music.play();musicBtn.classList.add('active');musicBtn.textContent='♫';musicPaused=false}catch(e){}}function unlockMusic(){if(!musicPaused&&music.paused)playMusic()}musicBtn.onclick=async()=>{if(music.paused){musicPaused=false;await playMusic()}else{music.pause();musicPaused=true;musicBtn.classList.remove('active');musicBtn.textContent='×'}};document.addEventListener('pointerdown',unlockMusic,{once:true});
for(let i=0;i<150;i++){const s=document.createElement('span');s.className='star';s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.animationDelay=Math.random()*4+'s';s.style.opacity=.15+Math.random()*.8;$('#stars').appendChild(s)}
function heart(symbol){const h=document.createElement('span');h.className='heart';h.textContent=symbol||['♡','♥','✦','✧'][Math.floor(Math.random()*4)];h.style.left=Math.random()*100+'%';h.style.bottom='-30px';h.style.fontSize=12+Math.random()*14+'px';h.style.animationDuration=5+Math.random()*4+'s';$('#hearts').appendChild(h);setTimeout(()=>h.remove(),9000)}
function petal(){const p=document.createElement('span');p.className='petal';p.style.left=Math.random()*100+'%';p.style.animationDuration=6+Math.random()*5+'s';$('#petals').appendChild(p);setTimeout(()=>p.remove(),11000)}setInterval(()=>heart(),1200);setInterval(petal,2200);
const envelope=$('#envelope'),letter=$('#letterContent');envelope.onclick=()=>{const open=envelope.classList.toggle('open');letter.classList.toggle('open',open);letter.setAttribute('aria-hidden',String(!open));$('#envelopeHint').textContent=open?'♡ From me to you.':'Tap the envelope.';if(open){burst(18);setTimeout(()=>letter.scrollIntoView({behavior:'smooth',block:'center'}),500)}};
let cakeBlown=false;function blowCake(){if(cakeBlown)return;cakeBlown=true;$('#cake').classList.add('blown');$('#wish').textContent='Wish made. ♡';$('#wish').classList.add('show');burst(30,'✦');for(let i=0;i<15;i++)setTimeout(petal,i*50)}$('#cake').onclick=blowCake;
$('#yesBtn').onclick=()=>{$('#answerMessage').textContent='Okay… then I guess I officially have permission to keep falling for you. ♡';$('#yesBtn').textContent='Best. Answer. Ever. ♡';$('#yesBtn').disabled=true;burst(45);for(let i=0;i<10;i++)setTimeout(petal,i*60)};$('#hugBtn').onclick=()=>{$('#answerMessage').textContent='Come here then, Boss. 🫂♡';burst(30)};
const glow=$('.cursor-glow');window.addEventListener('pointermove',e=>{if(glow)glow.style.left=e.clientX+'px',glow.style.top=e.clientY+'px'});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(e=>observer.observe(e));
goTo(0);setTimeout(()=>$('#swipeHint').style.opacity='.8',900);setTimeout(()=>$('#swipeHint').style.opacity='.2',6500);
